# Generated by Django 5.0 on 2024-11-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hamsafar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
